-- ==============================================================================
-- TecNM Residency System v2 - Migration 03: Companies & Agreements Expansion (N:M)
-- Idempotente y seguro para producción con datos existentes.
-- ==============================================================================

-- 1. Ampliar tabla companies con nombres y dirección estructurada (NULL por defecto)
ALTER TABLE companies ADD COLUMN IF NOT EXISTS legal_name VARCHAR(250) NULL;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS trade_name VARCHAR(150) NULL;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS street VARCHAR(150) NULL;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS number VARCHAR(50) NULL;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS colonia VARCHAR(150) NULL;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS city VARCHAR(100) NULL;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS state VARCHAR(100) NULL;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS postal_code VARCHAR(10) NULL;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS has_agreement BOOLEAN NOT NULL DEFAULT FALSE;

-- 2. Tabla de Convenios Institucionales
CREATE TABLE IF NOT EXISTS company_agreements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id VARCHAR(50) NULL,
    status VARCHAR(50) NOT NULL DEFAULT '1 VIGENTE', -- 1 VIGENTE, 2 VENCIDO, 3 STAND BY, 4 RENOVAR
    pit_code VARCHAR(20) NULL,                      -- 5.1.2, 5.1.3, 5.1.4
    cia_type VARCHAR(100) NULL,                     -- USO COMPARTIDO, DE VINCULACION ENTRE INSTITUTOS, CON IES
    agreement_scope VARCHAR(50) NULL,               -- GENERAL, ESPECIFICOS (Tipo 1)
    sector VARCHAR(50) NULL,                        -- PUBLICO, SOCIAL, PRIVADO, EDUCATIVO
    business_line VARCHAR(150) NULL,                -- Giro
    company_size VARCHAR(50) NULL,                  -- MICROEMPRESA, PEQUEÑAS EMPRESAS, MEDIANAS EMPRESAS, GRANDES EMPRESAS
    geographic_scope VARCHAR(50) NULL,              -- NACIONAL, INTERNACIONAL (Tipo 2)
    notes TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    deleted_by BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL
);

-- Si existía columna company_id con UNIQUE, remover restricción o columna para soportar N:M
ALTER TABLE company_agreements DROP COLUMN IF EXISTS company_id CASCADE;

CREATE INDEX IF NOT EXISTS ix_company_agreements_status ON company_agreements(status);
CREATE INDEX IF NOT EXISTS ix_company_agreements_archive_id ON company_agreements(archive_id);

-- 3. Tabla Pivote N:M entre Convenios y Empresas
CREATE TABLE IF NOT EXISTS agreement_companies (
    agreement_id BIGINT NOT NULL REFERENCES company_agreements(id) ON DELETE CASCADE,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (agreement_id, company_id)
);

CREATE INDEX IF NOT EXISTS ix_agreement_companies_company_id ON agreement_companies(company_id);
CREATE INDEX IF NOT EXISTS ix_agreement_companies_agreement_id ON agreement_companies(agreement_id);

-- 4. Actualizar vista de búsqueda de empresas
DROP VIEW IF EXISTS vw_search_companies CASCADE;
CREATE OR REPLACE VIEW vw_search_companies AS
SELECT 
    c.id AS id,
    c.name AS name,
    COALESCE(c.legal_name, '') AS legal_name,
    COALESCE(c.trade_name, '') AS trade_name,
    COALESCE(c.rfc, '') AS rfc,
    COALESCE(c.sector, '') AS sector,
    COALESCE(c.contact_name, '') AS contact_name,
    COALESCE(c.contact_email, '') AS contact_email,
    COALESCE(c.city, '') AS city,
    COALESCE(c.state, '') AS state,
    c.has_agreement AS has_agreement,
    c.is_active AS is_active
FROM companies c;
