namespace TecNM.Residency.Companies;

public record CompanyResponseDto(
    long Id,
    string Name,
    string? LegalName,
    string? TradeName,
    string? Rfc,
    string? Sector,
    string? Address,
    string? Street,
    string? Number,
    string? Colonia,
    string? City,
    string? State,
    string? PostalCode,
    string ContactName,
    string ContactEmail,
    string? ContactPhone,
    bool HasAgreement,
    bool IsActive,
    bool IsVisible,
    int DisplayOrder,
    long? CreatedBy,
    long? UpdatedBy,
    long? DeletedBy,
    DateTime? DeletedAt,
    DateTime CreatedAt,
    DateTime UpdatedAt
);
