-- ==============================================================================
-- Script 1: Esquema Estructurado y Semillas Esenciales (Producción & Desarrollo)
-- Sistema de Gestión de Residencias Profesionales TecNM v2
-- RDBMS: PostgreSQL 18+ (Compatible con EF Core AppDbContext)
-- Charset: UTF-8
-- ==============================================================================

BEGIN;

-- ------------------------------------------------------------------------------
-- Limpieza de Vistas y Tablas Previas (Drop Cascada)
-- ------------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_search_companies CASCADE;
DROP VIEW IF EXISTS vw_search_projects CASCADE;
DROP VIEW IF EXISTS vw_search_advisors CASCADE;
DROP VIEW IF EXISTS vw_search_students CASCADE;

DROP TABLE IF EXISTS advisory_sessions CASCADE;
DROP TABLE IF EXISTS evaluations CASCADE;
DROP TABLE IF EXISTS documents CASCADE;
DROP TABLE IF EXISTS weekly_progress CASCADE;
DROP TABLE IF EXISTS weekly_activities CASCADE;
DROP TABLE IF EXISTS project_objectives CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS companies CASCADE;
DROP TABLE IF EXISTS advisors CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS role_permissions CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS modules CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS "__EFMigrationsHistory" CASCADE;

-- ------------------------------------------------------------------------------
-- 1. Tabla: users (Autenticación y Usuarios)
-- ------------------------------------------------------------------------------
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    avatar_path VARCHAR(255) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    deleted_by BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE UNIQUE INDEX ix_users_email ON users (email);

-- ------------------------------------------------------------------------------
-- 2. Tabla: roles (Catálogo RBAC de Roles)
-- ------------------------------------------------------------------------------
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    deleted_by BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT uq_roles_code UNIQUE (code)
);

CREATE UNIQUE INDEX ix_roles_code ON roles (code);

-- ------------------------------------------------------------------------------
-- 3. Tabla: modules (Módulos del Sistema)
-- ------------------------------------------------------------------------------
CREATE TABLE modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    deleted_by BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT uq_modules_slug UNIQUE (slug)
);

CREATE UNIQUE INDEX ix_modules_slug ON modules (slug);

-- ------------------------------------------------------------------------------
-- 4. Tabla: permissions (Permisos Granulares por Módulo)
-- ------------------------------------------------------------------------------
CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(150) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    deleted_by BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_permissions_modules FOREIGN KEY (module_id) REFERENCES modules (id) ON DELETE CASCADE,
    CONSTRAINT uq_permissions_slug UNIQUE (slug)
);

CREATE INDEX ix_permissions_module_id ON permissions (module_id);
CREATE UNIQUE INDEX ix_permissions_slug ON permissions (slug);

-- ------------------------------------------------------------------------------
-- 5. Tabla: role_permissions (Mapeo de Permisos por Rol)
-- ------------------------------------------------------------------------------
CREATE TABLE role_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    deleted_by BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_role_permissions_roles FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permissions FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE,
    CONSTRAINT uq_role_permissions_role_permission UNIQUE (role_id, permission_id)
);

CREATE INDEX ix_role_permissions_permission_id ON role_permissions (permission_id);
CREATE UNIQUE INDEX ix_role_permissions_role_permission ON role_permissions (role_id, permission_id);

-- ------------------------------------------------------------------------------
-- 6. Tabla: user_roles (Asignación de Roles a Usuarios)
-- ------------------------------------------------------------------------------
CREATE TABLE user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    deleted_by BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_user_roles_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_roles FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT uq_user_roles_user_role UNIQUE (user_id, role_id)
);

CREATE INDEX ix_user_roles_role_id ON user_roles (role_id);
CREATE UNIQUE INDEX ix_user_roles_user_role ON user_roles (user_id, role_id);

-- ------------------------------------------------------------------------------
-- 7. Tabla: students (Perfiles de Estudiantes)
-- ------------------------------------------------------------------------------
CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    control_number VARCHAR(20) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name_1 VARCHAR(100) NOT NULL,
    last_name_2 VARCHAR(100) NULL,
    curp VARCHAR(20) NULL,
    gender VARCHAR(20) NULL,
    career_id BIGINT NOT NULL,
    academic_period_id INT NULL,
    advisor_id BIGINT NULL,
    gpa NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    deleted_by BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_students_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_students_user_id UNIQUE (user_id),
    CONSTRAINT uq_students_control_number UNIQUE (control_number)
);

CREATE UNIQUE INDEX ix_students_user_id ON students (user_id);
CREATE UNIQUE INDEX ix_students_control_number ON students (control_number);

-- ------------------------------------------------------------------------------
-- 8. Tabla: advisors (Perfiles de Asesores)
-- ------------------------------------------------------------------------------
CREATE TABLE advisors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    advisor_type TEXT NOT NULL DEFAULT 'Internal',
    full_name VARCHAR(200) NOT NULL,
    title VARCHAR(100) NULL,
    phone VARCHAR(30) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    deleted_by BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_advisors_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_advisors_user_id ON advisors (user_id);

-- ------------------------------------------------------------------------------
-- 8.1. Tabla: career_heads (Perfiles de Jefes de Carrera)
-- ------------------------------------------------------------------------------
CREATE TABLE career_heads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE NOT NULL,
    career_id BIGINT NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    title VARCHAR(50) NULL,
    phone VARCHAR(20) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    deleted_by BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_career_heads_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_career_heads_user_id ON career_heads (user_id);
CREATE INDEX ix_career_heads_career_id ON career_heads (career_id);

-- ------------------------------------------------------------------------------
-- 9. Tabla: companies (Empresas Receptoras)
-- ------------------------------------------------------------------------------
CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    rfc VARCHAR(13) NOT NULL,
    sector VARCHAR(100) NULL,
    address VARCHAR(300) NULL,
    contact_name VARCHAR(150) NOT NULL,
    contact_email VARCHAR(150) NOT NULL,
    contact_phone VARCHAR(30) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    deleted_by BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL
);

CREATE INDEX ix_companies_rfc ON companies (rfc);

-- ------------------------------------------------------------------------------
-- 10. Tabla: projects (Anteproyectos de Residencia)
-- ------------------------------------------------------------------------------
CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    advisor_id BIGINT NULL,
    company_id BIGINT NOT NULL,
    title VARCHAR(250) NOT NULL,
    project_type VARCHAR(100) NULL,
    problem_statement TEXT NOT NULL,
    justification TEXT NOT NULL,
    general_objective TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    start_date TIMESTAMP WITH TIME ZONE NULL,
    end_date TIMESTAMP WITH TIME ZONE NULL,
    review_comments TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    deleted_by BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_projects_students FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE,
    CONSTRAINT fk_projects_advisors FOREIGN KEY (advisor_id) REFERENCES advisors (id) ON DELETE NO ACTION,
    CONSTRAINT fk_projects_companies FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE RESTRICT
);

CREATE INDEX ix_projects_student_id ON projects (student_id);
CREATE INDEX ix_projects_advisor_id ON projects (advisor_id);
CREATE INDEX ix_projects_company_id ON projects (company_id);

-- ------------------------------------------------------------------------------
-- 11. Tabla: project_objectives (Objetivos Específicos)
-- ------------------------------------------------------------------------------
CREATE TABLE project_objectives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    objective_number INT NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    notes TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    deleted_by BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_project_objectives_projects FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT uq_project_objectives_project_number UNIQUE (project_id, objective_number)
);

CREATE UNIQUE INDEX ix_project_objectives_project_number ON project_objectives (project_id, objective_number);

-- ------------------------------------------------------------------------------
-- 12. Tabla: weekly_activities (Cronograma de Actividades)
-- ------------------------------------------------------------------------------
CREATE TABLE weekly_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    activity_number INT NOT NULL,
    title VARCHAR(250) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    deleted_by BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_weekly_activities_projects FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);

CREATE INDEX ix_weekly_activities_project_id ON weekly_activities (project_id);

-- ------------------------------------------------------------------------------
-- 13. Tabla: weekly_progress (Avances Semanales 1-26)
-- ------------------------------------------------------------------------------
CREATE TABLE weekly_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id BIGINT NOT NULL,
    week_number INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    notes TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    deleted_by BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_weekly_progress_weekly_activities FOREIGN KEY (activity_id) REFERENCES weekly_activities (id) ON DELETE CASCADE,
    CONSTRAINT uq_weekly_progress_activity_week UNIQUE (activity_id, week_number)
);

CREATE UNIQUE INDEX ix_weekly_progress_activity_week ON weekly_progress (activity_id, week_number);

-- ------------------------------------------------------------------------------
-- 14. Tabla: documents (Expediente Digital)
-- ------------------------------------------------------------------------------
CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    document_type VARCHAR(50) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,
    content_type VARCHAR(100) NOT NULL DEFAULT 'application/pdf',
    status VARCHAR(50) NOT NULL DEFAULT 'uploaded',
    rejection_reason TEXT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    deleted_by BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_documents_projects FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);

CREATE INDEX ix_documents_project_id ON documents (project_id);

-- ------------------------------------------------------------------------------
-- 15. Tabla: evaluations (Calificaciones y Evaluaciones)
-- ------------------------------------------------------------------------------
CREATE TABLE evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    evaluator_id BIGINT NOT NULL,
    evaluation_period VARCHAR(30) NOT NULL,
    score NUMERIC(5,2) NOT NULL,
    feedback TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    deleted_by BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_evaluations_projects FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);

CREATE INDEX ix_evaluations_project_id ON evaluations (project_id);

-- ------------------------------------------------------------------------------
-- 16. Tabla: advisory_sessions (Bitácora de Asesorías)
-- ------------------------------------------------------------------------------
CREATE TABLE advisory_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    advisor_id BIGINT NOT NULL,
    session_date TIMESTAMP WITH TIME ZONE NOT NULL,
    topics_covered TEXT NOT NULL,
    student_agreements TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    deleted_by BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_advisory_sessions_projects FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_advisory_sessions_advisors FOREIGN KEY (advisor_id) REFERENCES advisors (id) ON DELETE NO ACTION
);

CREATE INDEX ix_advisory_sessions_project_id ON advisory_sessions (project_id);
CREATE INDEX ix_advisory_sessions_advisor_id ON advisory_sessions (advisor_id);

-- ==============================================================================
-- VISTAS DE BÚSQUEDA GLOBAL
-- ==============================================================================
CREATE VIEW vw_search_students AS
SELECT 
    s.id AS id,
    s.control_number AS control_number,
    CONCAT(s.first_name, ' ', s.last_name_1, COALESCE(' ' || s.last_name_2, '')) AS full_name,
    COALESCE(u.email, '') AS email,
    COALESCE(s.curp, '') AS curp,
    s.career_id AS career_id,
    s.is_active AS is_active
FROM students s
LEFT JOIN users u ON s.user_id = u.id
WHERE u.role IS NULL OR u.role IN ('student', 'Student');

CREATE VIEW vw_search_advisors AS
SELECT 
    a.id AS id,
    a.full_name AS full_name,
    COALESCE(a.title, '') AS title,
    a.advisor_type::text AS advisor_type,
    a.department_id AS department_id,
    COALESCE(u.email, '') AS email,
    COALESCE(a.phone, '') AS phone,
    a.is_active AS is_active
FROM advisors a
LEFT JOIN users u ON a.user_id = u.id
WHERE u.role IS NULL OR u.role IN ('advisor', 'academico', 'Advisor', 'Academic');

CREATE VIEW vw_search_projects AS
SELECT 
    p.id AS id,
    p.title AS title,
    COALESCE(p.project_type, '') AS project_type,
    p.status::text AS status,
    CONCAT(s.first_name, ' ', s.last_name_1) AS student_name,
    COALESCE(a.full_name, 'Sin Asignar') AS advisor_name,
    COALESCE(c.name, 'Sin Empresa') AS company_name,
    p.advisor_id AS advisor_id,
    p.is_active AS is_active
FROM projects p
LEFT JOIN students s ON p.student_id = s.id
LEFT JOIN advisors a ON p.advisor_id = a.id
LEFT JOIN companies c ON p.company_id = c.id
WHERE p.status <> 'draft';

CREATE VIEW vw_search_companies AS
SELECT 
    c.id AS id,
    c.name AS name,
    c.rfc AS rfc,
    COALESCE(c.sector, '') AS sector,
    COALESCE(c.contact_name, '') AS contact_name,
    COALESCE(c.contact_email, '') AS contact_email,
    c.is_active AS is_active
FROM companies c;

-- ==============================================================================
-- INSERCIONES DML: SEMILLAS ESENCIALES (RBAC Y SUPER ADMIN)
-- ==============================================================================

-- 1. Sembrado de Módulos (9 Módulos Oficiales)
INSERT INTO modules (code, name, slug, is_active, display_order) VALUES
('M01', 'Estudiantes', 'students', true, 1),
('M02', 'Anteproyectos', 'projects', true, 2),
('M03', 'Cronograma y Actividades', 'activities', true, 3),
('M04', 'Bitácora de Asesorías', 'advisories', true, 4),
('M05', 'Evaluaciones', 'evaluations', true, 5),
('M06', 'Expediente Documental', 'documents', true, 6),
('M07', 'Empresas e Instituciones', 'companies', true, 7),
('M08', 'Reportes y Métricas', 'reports', true, 8),
('M09', 'Administración del Sistema', 'admin', true, 9)
ON CONFLICT (slug) DO NOTHING;

-- 2. Sembrado de Permisos (37 Permisos Granulares)
INSERT INTO permissions (module_id, name, slug, is_active) VALUES
-- Estudiantes
((SELECT id FROM modules WHERE slug = 'students'), 'Ver Perfil de Estudiante', 'students.profile.view', true),
((SELECT id FROM modules WHERE slug = 'students'), 'Actualizar Perfil', 'students.profile.update', true),
((SELECT id FROM modules WHERE slug = 'students'), 'Verificar Elegibilidad', 'students.eligibility.verify', true),
((SELECT id FROM modules WHERE slug = 'students'), 'Gestión de Estudiantes', 'students.manage', true),
((SELECT id FROM modules WHERE slug = 'students'), 'Gestión de Asesores', 'advisors.manage', true),

-- Anteproyectos
((SELECT id FROM modules WHERE slug = 'projects'), 'Solicitud y Registro de Anteproyecto', 'projects.proposals', true),
((SELECT id FROM modules WHERE slug = 'projects'), 'Crear Propuesta de Anteproyecto', 'projects.proposal.create', true),
((SELECT id FROM modules WHERE slug = 'projects'), 'Editar Anteproyecto', 'projects.proposal.update', true),
((SELECT id FROM modules WHERE slug = 'projects'), 'Dictamen de División', 'projects.review', true),
((SELECT id FROM modules WHERE slug = 'projects'), 'Eliminación Lógica de Anteproyectos', 'projects.delete', true),
((SELECT id FROM modules WHERE slug = 'projects'), 'Asignar Asesor Académico', 'projects.advisor.assign', true),
((SELECT id FROM modules WHERE slug = 'projects'), 'Ver Mis Anteproyectos', 'projects.my', true),
((SELECT id FROM modules WHERE slug = 'projects'), 'Ver Anteproyectos Asignados', 'projects.advisor', true),
((SELECT id FROM modules WHERE slug = 'projects'), 'Gestión de Anteproyectos', 'projects.manage', true),

-- Actividades
((SELECT id FROM modules WHERE slug = 'activities'), 'Cronograma de Actividades 26 Semanas', 'activities.schedule', true),
((SELECT id FROM modules WHERE slug = 'activities'), 'Reportar Avance Semanal', 'activities.progress.report', true),
((SELECT id FROM modules WHERE slug = 'activities'), 'Validar Avance Semanal', 'activities.progress.validate', true),

-- Asesorías
((SELECT id FROM modules WHERE slug = 'advisories'), 'Bitácora de Asesorías', 'evaluations.advisories', true),
((SELECT id FROM modules WHERE slug = 'advisories'), 'Registrar Sesión de Asesoría', 'advisories.session.record', true),
((SELECT id FROM modules WHERE slug = 'advisories'), 'Ver Bitácora de Asesorías', 'advisories.session.view', true),
((SELECT id FROM modules WHERE slug = 'advisories'), 'Subir Evidencia de Asesoría', 'advisories.evidence.upload', true),

-- Evaluaciones
((SELECT id FROM modules WHERE slug = 'evaluations'), 'Evaluaciones y Calificaciones', 'evaluations.grading', true),
((SELECT id FROM modules WHERE slug = 'evaluations'), 'Evaluar Parciales 1 y 2', 'evaluations.grade.partial', true),
((SELECT id FROM modules WHERE slug = 'evaluations'), 'Evaluar Reporte Final', 'evaluations.grade.final', true),
((SELECT id FROM modules WHERE slug = 'evaluations'), 'Ver Resumen de Evaluaciones', 'evaluations.summary.view', true),

-- Documentos
((SELECT id FROM modules WHERE slug = 'documents'), 'Expediente Digital', 'documents.digital', true),
((SELECT id FROM modules WHERE slug = 'documents'), 'Subir Documentos de Expediente', 'documents.upload', true),
((SELECT id FROM modules WHERE slug = 'documents'), 'Verificar Expediente', 'documents.verify', true),
((SELECT id FROM modules WHERE slug = 'documents'), 'Generar Cartas Presentación/Liberación', 'documents.letters.generate', true),
((SELECT id FROM modules WHERE slug = 'documents'), 'Ver Mis Documentos', 'documents.my', true),

-- Empresas
((SELECT id FROM modules WHERE slug = 'companies'), 'Ver Catálogo de Empresas', 'companies.view', true),
((SELECT id FROM modules WHERE slug = 'companies'), 'Alta de Empresa', 'companies.create', true),
((SELECT id FROM modules WHERE slug = 'companies'), 'Gestión de Empresas', 'companies.manage', true),

-- Reportes
((SELECT id FROM modules WHERE slug = 'reports'), 'Reportes y Métricas', 'admin.reports', true),
((SELECT id FROM modules WHERE slug = 'reports'), 'Exportar Reportes en Excel', 'reports.export.excel', true),

-- Admin
((SELECT id FROM modules WHERE slug = 'admin'), 'Administración de Usuarios', 'admin.users.manage', true),
((SELECT id FROM modules WHERE slug = 'admin'), 'Administración de Roles y Permisos', 'admin.roles', true),
((SELECT id FROM modules WHERE slug = 'admin'), 'Administración de Catálogos', 'admin.catalogs.manage', true)
ON CONFLICT (slug) DO NOTHING;

-- 3. Sembrado de Roles (6 Roles Oficiales)
INSERT INTO roles (code, name, description, is_active, display_order) VALUES
('admin', 'Super Administrador', 'Control total del sistema y gestión global', true, 1),
('academico', 'Académicos y Jefatura', 'Alta y gestión de alumnos/asesores, dictamen y elegibilidad', true, 2),
('vinculacion', 'Gestión Tecnológica y Vinculación', 'Alta de empresas, solicitudes de perfiles, cartas de presentación y expedientes', true, 3),
('director', 'Director / Directivos', 'Acceso de solo lectura global a todos los módulos', true, 4),
('advisor', 'Asesores Académicos', 'Asesoría académica, revisión de 26 semanas y evaluación', true, 5),
('student', 'Estudiantes', 'Registro de anteproyectos vinculados a empresas, cronograma y expediente', true, 6)
ON CONFLICT (code) DO NOTHING;

-- 4. Asignación de Permisos por Rol (role_permissions)
-- Rol: Admin (Todos los Permisos)
INSERT INTO role_permissions (role_id, permission_id, is_active)
SELECT (SELECT id FROM roles WHERE code = 'admin'), p.id, true
FROM permissions p
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Rol: Académico y Jefatura
INSERT INTO role_permissions (role_id, permission_id, is_active)
SELECT (SELECT id FROM roles WHERE code = 'academico'), p.id, true
FROM permissions p
WHERE p.slug IN (
    'students.profile.view', 'students.profile.update', 'students.eligibility.verify', 'students.manage', 'advisors.manage',
    'projects.proposals', 'projects.proposal.update', 'projects.review', 'projects.delete', 'projects.advisor.assign', 'projects.manage',
    'activities.schedule', 'activities.progress.validate',
    'evaluations.advisories', 'advisories.session.view', 'evaluations.summary.view',
    'documents.digital', 'documents.upload', 'documents.verify',
    'companies.view'
)
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Rol: Vinculación
INSERT INTO role_permissions (role_id, permission_id, is_active)
SELECT (SELECT id FROM roles WHERE code = 'vinculacion'), p.id, true
FROM permissions p
WHERE p.slug IN (
    'companies.view', 'companies.create', 'companies.manage',
    'documents.digital', 'documents.verify', 'documents.letters.generate',
    'students.profile.view', 'advisors.manage', 'projects.proposals', 'projects.review',
    'admin.reports', 'reports.export.excel'
)
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Rol: Director
INSERT INTO role_permissions (role_id, permission_id, is_active)
SELECT (SELECT id FROM roles WHERE code = 'director'), p.id, true
FROM permissions p
WHERE p.slug IN (
    'students.profile.view', 'advisors.manage', 'projects.proposals', 'activities.schedule',
    'advisories.session.view', 'evaluations.summary.view', 'documents.digital', 'companies.view',
    'admin.reports', 'reports.export.excel'
)
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Rol: Asesor Académico
INSERT INTO role_permissions (role_id, permission_id, is_active)
SELECT (SELECT id FROM roles WHERE code = 'advisor'), p.id, true
FROM permissions p
WHERE p.slug IN (
    'projects.review', 'projects.advisor',
    'activities.schedule', 'activities.progress.validate',
    'evaluations.advisories', 'advisories.session.record', 'advisories.session.view',
    'evaluations.grading', 'evaluations.grade.partial', 'evaluations.grade.final', 'evaluations.summary.view',
    'documents.digital', 'documents.verify'
)
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Rol: Estudiante
INSERT INTO role_permissions (role_id, permission_id, is_active)
SELECT (SELECT id FROM roles WHERE code = 'student'), p.id, true
FROM permissions p
WHERE p.slug IN (
    'students.profile.view', 'students.profile.update',
    'projects.proposals', 'projects.proposal.create', 'projects.proposal.update', 'projects.my',
    'activities.schedule', 'activities.progress.report',
    'evaluations.advisories', 'advisories.session.view', 'advisories.evidence.upload',
    'documents.digital', 'documents.upload', 'documents.my',
    'companies.view'
)
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- 5. Usuario Super Administrador Semilla (admin@monclova.tecnm.mx / Admin2026!)
-- Hash BCrypt para 'Admin2026!': $2a$11$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy
INSERT INTO users (email, password_hash, role, is_admin, is_active)
VALUES (
    'admin@monclova.tecnm.mx',
    '$2a$11$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',
    'Admin',
    true,
    true
)
ON CONFLICT (email) DO NOTHING;

-- Asignación de rol al usuario Admin
INSERT INTO user_roles (user_id, role_id, is_active)
SELECT 
    u.id, 
    r.id, 
    true
FROM users u
CROSS JOIN roles r
WHERE u.email = 'admin@monclova.tecnm.mx' AND r.code = 'admin'
ON CONFLICT (user_id, role_id) DO NOTHING;

COMMIT;
