using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TecNM.Residency.Migrations
{
    /// <inheritdoc />
    public partial class AddCompanies : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS companies (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name character varying(200) NOT NULL,
                    rfc character varying(13) NOT NULL,
                    sector character varying(100) NULL,
                    address character varying(300) NULL,
                    contact_name character varying(150) NOT NULL,
                    contact_email character varying(150) NOT NULL,
                    contact_phone character varying(30) NULL,
                    is_active boolean NOT NULL DEFAULT TRUE,
                    is_visible boolean NOT NULL DEFAULT TRUE,
                    display_order integer NOT NULL DEFAULT 0,
                    created_by bigint NULL,
                    updated_by bigint NULL,
                    deleted_by bigint NULL,
                    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
                    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
                    deleted_at timestamp with time zone NULL
                );

                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='companies' AND column_name='name') THEN
                        IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='companies' AND column_name='legal_name') THEN
                            ALTER TABLE companies RENAME COLUMN legal_name TO name;
                        ELSE
                            ALTER TABLE companies ADD COLUMN name character varying(200) NOT NULL DEFAULT '';
                        END IF;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='companies' AND column_name='sector') THEN
                        IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='companies' AND column_name='industry_sector') THEN
                            ALTER TABLE companies RENAME COLUMN industry_sector TO sector;
                        ELSE
                            ALTER TABLE companies ADD COLUMN sector character varying(100) NULL;
                        END IF;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='companies' AND column_name='contact_name') THEN
                        IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='companies' AND column_name='contact_person') THEN
                            ALTER TABLE companies RENAME COLUMN contact_person TO contact_name;
                        ELSE
                            ALTER TABLE companies ADD COLUMN contact_name character varying(150) NOT NULL DEFAULT '';
                        END IF;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='companies' AND column_name='contact_email') THEN
                        IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='companies' AND column_name='email') THEN
                            ALTER TABLE companies RENAME COLUMN email TO contact_email;
                        ELSE
                            ALTER TABLE companies ADD COLUMN contact_email character varying(150) NOT NULL DEFAULT '';
                        END IF;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='companies' AND column_name='contact_phone') THEN
                        IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='companies' AND column_name='phone') THEN
                            ALTER TABLE companies RENAME COLUMN phone TO contact_phone;
                        ELSE
                            ALTER TABLE companies ADD COLUMN contact_phone character varying(30) NULL;
                        END IF;
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS ix_companies_rfc ON companies (rfc);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "companies");
        }
    }
}
